### PR TITLE
Major test_va_api refactoring and bug fixes

### LINKED ISSUE #86: TEST_P(VAAPIGetCreateConfig, CreateConfigWithAttributes)
this test call (line 63/66 of test_va_api_get_create_config.cpp)
doGetConfigAttributes(currentProfile,currentEntrypoint);
doCreateConfigWithAttrib(currentProfile,currentEntrypoint);
I don't think that the attributes from vaGetConfigAttributes can be directly used for vaCreateConfig
for example:
if (attrib[type] == VAConfigAttribRateControl && attrb[value] == 0x6) it means VBR & CBR support, but not mean you can set VBR|CBR directly to vaCreateConfig, right?

### LINKED ISSUE #91: SurfaceAttributes should not be set  together
when we call vaQuerySurfaceAttributes, for the attributes type == VASurfaceAttribMemoryType, driver may report several support memory type method, but it does not means you can set it directly into driver by vaCreateSurfaces.  for example, if you set the value tobe VA_SURFACE_ATTRIB_MEM_TYPE_VA |    VA_SURFACE_ATTRIB_MEM_TYPE_USER_PTR |VA_SURFACE_ATTRIB_MEM_TYPE_KERNEL_DRM | VA_SURFACE_ATTRIB_MEM_TYPE_DRM_PRIME = 0x30000005, but if vaCreateSurfaces set the value to be 0x30000005, driver certainly does not know the real memory type. it will block the test cases.

### LINKED ISSUE #92: should not use the value returned from vaGetConfigAttributes directly for vaCreateConfig
CreateSurfaces/VAAPICreateSurfaces.CreateSurfacesWithCofigAttribs/2226 ,
TEST_P(VAAPICreateSurfaces, CreateSurfacesWithCofigAttribs)
            doGetConfigAttributes(currentProfile,
                                                currentEntrypoint);

            doQuerySurfacesWithConfigAttribs(currentProfile,
                                                   currentEntrypoint);

if driver support both VA_DEC_SLICE_MODE_NORMAL | VA_DEC_SLICE_MODE_BASE for VAConfigAttribDecSliceMode , it will failed.

### PR DESCRIPTION
**Pull request by uartie**
The pre-existing test_va_api test suite was inflexible and stuffed way too much logic/control into the primary test fixture.  Also, there were quite a few bad test assumptions and/or bugs in regards to bitfield config and surface attributes.  This patch series addresses most of these issues and fixes a few bugs.

Fixes #86
Fixes #91
Fixes #92

### CODE REVIEW

**Comment by uartie** [comment]
@jayesht could you help review?

**Comment by uartie** [comment]
@XinfengZhang  could you help review?

**Comment by uartie** [comment]
Note that there are 30 new i965 test failures in `GetCreateConfig/VAAPIGetCreateConfig.CreateConfigWithAttributes` with these patches.  Those failures are "real" bugs in the driver that did not get caught by previous test logic.

File: test/test_va_api_config_attribs.cpp [hunk 1]
```diff
@@ -39,40 +40,106 @@ class VAAPIConfigAttribs
...
+        if (doFindEntrypointInList(entrypoint)) {
+            // create config without attributes (i.e. use driver defaults)
+            createConfig(profile, entrypoint);
 
-        for (const auto& entrypoint : entrypoints) {
-            doGetMaxNumConfigAttribs();
-            doCreateConfigNoAttrib(profile, entrypoint);
+            // query default attributes from the config we just created
+            ConfigAttributes actual;
+            queryConfigAttributes(profile, entrypoint, actual);
```
Comment (jayesht) [inline test/test_va_api_config_attribs.cpp]: When queryConfigAttributes returns actual.clear() in case of error, proceeding further may not be logical.

File: test/test_va_api_config_attribs.cpp [hunk 2]
```diff
@@ -39,40 +40,106 @@ class VAAPIConfigAttribs
...
-            doCheckAttribsMatch(attribs);
-            doDestroyConfig();
+            // get supported config attribute values
+            getConfigAttributes(profile, entrypoint, supported);
+
+            // verify actual config attribute values are supported values
+            validateConfigAttributes(actual, supported);
+        } else {
+            // entrypoint not supported
+            doLogSkipTest(profile, entrypoint);
```
Comment (jayesht) [inline test/test_va_api_config_attribs.cpp]: Feature request: doLogSkipTest should be able to differentiate between unsupported Profile and unsupported entrypoint. Better, should be made generic to accept any types or arguments for skipped tests. Not sure if I should be raising a feature request bug for this :)

File: test/test_va_api_config_attribs.cpp (hunk 1 above)
Comment (uartie) [reply test/test_va_api_config_attribs.cpp]: I disagree.  If it fails, we still need to call `destroyConfig()`... and all other calls after that have proper checks in place to fail appropriately, too (i.e. it won't crash because of empty attributes).  In general, tests should only need to stop proceeding if a failure would cause test to crash in later operations.

File: test/test_va_api_config_attribs.cpp (hunk 2 above)
Comment (uartie) [reply test/test_va_api_config_attribs.cpp]: Out of scope for current PR.  Please file feature request.

Comment (jayesht) [reply test/test_va_api_config_attribs.cpp]: https://github.com/01org/libva-utils/issues/99 opened as feature request bug.

File: test/test_va_api_config_attribs.cpp (hunk 1 above)
Comment (jayesht) [reply test/test_va_api_config_attribs.cpp]: +1 for "In general, tests should only need to stop proceeding if a failure would cause test to crash in later operations." and "proper checks in place to fail appropriately, too"

In this case Failure will be caught downstream, which allows error propagation rather than catching failure locally. I agree that tests should proceed in non-fatal failures but erroring out locally is probably better for debug.

File: test/test_va_api_config_attribs.cpp [hunk 3]
```diff
@@ -39,40 +40,106 @@ class VAAPIConfigAttribs
...
+        ASSERT_EQ(size, supported.size());
+
+        // Require that actual and supported are in the same order, by type
+        for (size_t i(0); i < size; ++i) {
+            const VAConfigAttrib& aAttrib = actual[i];
+            const VAConfigAttrib& sAttrib = supported[i];
+
+            ASSERT_EQ(aAttrib.type, sAttrib.type);
+
+            switch (aAttrib.type) {
```
Comment (jayesht) [inline test/test_va_api_config_attribs.cpp]: Just to make a note: not all aAttrib.type are covered under this switch case. There are other bit field cases which needs to be covered. ie. VAConfigAttribFEIFunctionType and more. This should be in #ToDo list.

File: test/test_va_api_config_attribs.cpp [hunk 4]
```diff
@@ -39,40 +40,106 @@ class VAAPIConfigAttribs
...
+            case VAConfigAttribRTFormat:
+                EXPECT_EQ(sAttrib.value & aAttrib.value, aAttrib.value);
+                break;
+
+            // The following type's return a bitfield of supported choices
```
Comment (jayesht) [inline test/test_va_api_config_attribs.cpp]: Just to make a note: not all aAttrib.type are covered under this switch case. There are other bit field cases which needs to be covered. ie. VAConfigAttribFEIFunctionType and more. This should be in #ToDo list.

File: test/test_va_api_config_attribs.cpp [hunk 5]
```diff
@@ -28,6 +28,7 @@ namespace VAAPI {
 
 class VAAPIConfigAttribs
     : public VAAPIFixture
+    , public ::testing::WithParamInterface<std::tuple<VAProfile, VAEntrypoint> >
```
Comment (jayesht) [inline test/test_va_api_config_attribs.cpp]: Pedantic, but ::pair could suffice.

Comment (uartie) [reply test/test_va_api_config_attribs.cpp]: tuple is nicer so you can use ::testing::get<n>

Comment (uartie) [reply test/test_va_api_config_attribs.cpp]: hah, nvmind... looks like std::pair supports `get<n>` too ;)

**Comment by uartie** [comment]
> Note that there are 30 new i965 test failures in GetCreateConfig/VAAPIGetCreateConfig.CreateConfigWithAttributes with these patches. Those failures are "real" bugs in the driver that did not get caught by previous test logic.

I have filed 01org/intel-vaapi-driver#336 and 01org/intel-vaapi-driver#337 for these new failures

File: test/test_va_api_config_attribs.cpp (hunk 4 above)
Comment (uartie) [reply test/test_va_api_config_attribs.cpp]: There is a question as to whether these test requirements are correct to begin with.  That is, is it legal for driver to return the same bitfield value (i.e. all supported bitmasks) in `vaQueryConfigAttributes` as returned from `vaGetConfigAttributes` if user/app did not explicitly specify a attribute value during `vaCreateConfig`.  Currently, iHD driver does this and fails these tests (for the currently covered bitfield attribute types) since this test expects `vaQueryConfigAttributes` to return the *actual* attribute value being used.

For example, `vaGetConfigAttributes` might return `VAConfigAttribRateControl=VA_RC_VBR | VA_RC_CBR | VA_RC_CQP` and user might call `vaCreateConfig` without `VAConfigAttribRateControl` attribute set.  In this case, driver should choose *one* default value for `VAConfigAttribRateControl`.  Question is, when `vaQueryConfigAttributes` is called for that config, should the driver return the default `VAConfigAttribRateControl` value it chose during `vaCreateConfig` or should it return all possible supported values as returned from `vaGetConfigAttributes` (or just not return a `VAConfigAttribRateControl` at all when not specified by user/app)?

Comment (uartie) [reply test/test_va_api_config_attribs.cpp]: > ...Question is, when vaQueryConfigAttributes is called for that config, should the driver return the default VAConfigAttribRateControl value it chose during vaCreateConfig or should it return all possible supported values as returned from vaGetConfigAttributes (or just not return a VAConfigAttribRateControl at all when not specified by user/app)?

After a little more investigation, both i965 and iHD do the latter two (of 3) behaviors.  i965 just chooses the last behavior for most attributes, which is why it passes more tests than iHD.  Thus, I'll change this test to behave like the current "default" case for all attributes, if that seems reasonable.

**Comment by uartie** [comment]
updated the "test/config_attribs: use new fixture config methods" patch to relax constraints and handle more bitfield-type config attributes

File: test/test_va_api_fixture.cpp [hunk 6]
```diff
@@ -367,6 +367,135 @@ void VAAPIFixture::doDestroyConfig()
...
+        }
+    }
+}
+
+void VAAPIFixture::destroySurfaces(Surfaces& surfaces) const
+{
+    if (surfaces.size() != 0) {
+        EXPECT_STATUS(vaDestroySurfaces(m_vaDisplay, surfaces.data(),
+            surfaces.size()));
+    }
```
[the remark this answers is not in the document]
Comment (uartie) [reply test/test_va_api_fixture.cpp]: I think this should be left up to the test case to decide.  If vaDestroySurfaces fails for some reason, then VASurfaceID's might still be valid (and not destroyed), in which case, the test might be able to correct the behavior somehow.

[the remark this answers is not in the document]
Comment (uartie) [reply test/test_va_api_fixture.cpp]: Also, a test case might want to retain surface ids, to verify what happens when vaDestroySurface is called a second time on an already destroyed surface id.

File: test/test_va_api_fixture.cpp [hunk 7]
```diff
@@ -367,6 +367,135 @@ void VAAPIFixture::doDestroyConfig()
...
+    attribs.resize(numAttribs);
+
+    const uint32_t flags = 0x0 | VA_SURFACE_ATTRIB_GETTABLE
+        | VA_SURFACE_ATTRIB_SETTABLE;
+
+    for (const auto& attrib : attribs) {
+        EXPECT_NE(attrib.flags & flags,
+            (uint32_t)VA_SURFACE_ATTRIB_NOT_SUPPORTED);
+        EXPECT_GE(attrib.value.type, VAGenericValueTypeInteger);
+        EXPECT_LE(attrib.value.type, VAGenericValueTypeFunc);
```
Comment (jayesht) [inline test/test_va_api_fixture.cpp]: I could not find reference to these in libva spec.

Comment (uartie) [reply test/test_va_api_fixture.cpp]: These checks just ensure that the generic type is one of the VAGenericValueType enum values.  It is the same check used in the legacy doQuerySurfaceAttributes.

Comment (jayesht) [reply test/test_va_api_fixture.cpp]: The enum has VAGenericValueTypeFunc. No SurfaceAttributes are of type Func. So checking less than or equal to TypeFunc seems wrong. Not sure why was it introduced in legacy test, though. 
libva-utils tests should adhere to libva spec only, imo.

Comment (uartie) [reply test/test_va_api_fixture.cpp]: Please go back and study the VASurfaceAttrib data structure again... it has a VAGenericValue member field called `value`.  The checks here are checking the `attrib.value.type`, not the `attrib.type`.

File: test/test_va_api_get_create_config.cpp [hunk 8]
```diff
@@ -54,19 +56,70 @@ TEST_P(VAAPIGetCreateConfig, CreateConfigWithAttributes)
...
+
+            // create config with each individual supported attribute
+            for (const auto& attrib : attribs) {
+                const auto match = g_vaConfigAttribBitMasks.find(attrib.type);
+                if (match != g_vaConfigAttribBitMasks.end()) {
+                    // it's a bitfield attribute
+                    uint32_t bitfield(0);
+                    const BitMasks& masks = match->second;
+                    for (const auto mask : masks) { // for all bitmasks
+                        const bool isSet((attrib.value & mask) == mask);
```
Comment (xhaihao) [inline test/test_va_api_get_create_config.cpp]: Some flags are not bitmask in va.h, e.g. VA_ENC_PACKED_HEADER_NONE is defined as '0' in va.h.

File: test/test_va_api_get_create_config.cpp [hunk 9]
```diff
@@ -54,19 +56,70 @@ TEST_P(VAAPIGetCreateConfig, CreateConfigWithAttributes)
...
+                                  VA_STATUS_ERROR_INVALID_VALUE);
+                            createConfig(profile, entrypoint,
+                                ConfigAttributes(
+                                    1, {type : attrib.type, value : mask}),
+                                expectation);
+                            destroyConfig(VA_STATUS_ERROR_INVALID_CONFIG);
+                        }
+                    }
+                    // ensure we processed all supported values
+                    EXPECT_EQ(bitfield, attrib.value);
```
Comment (xhaihao) [inline test/test_va_api_get_create_config.cpp]: VA_ENC_PACKED_HEADER_MISC is still used by some app, e.g. FFmpeg, so our driver still supports VA_ENC_PACKED_HEADER_MISC. however VA_ENC_PACKED_HEADER_MISC isn't included in gtest, so we can't use EXPECT_EQ for g_vaEncPackedHeaders.

File: test/test_va_api_fixture.cpp (hunk 7 above)
Comment (jayesht) [reply test/test_va_api_fixture.cpp]: My mistake. Peace.

File: test/test_va_api_get_create_config.cpp (hunk 8 above)
Comment (uartie) [reply test/test_va_api_get_create_config.cpp]: Yes, thanks for catching this.  I'll remove VA_ENC_PACKED_HEADER_NONE and VA_ENC_INTERLACED_NONE from the bitmask containers.

File: test/test_va_api_get_create_config.cpp (hunk 9 above)
Comment (uartie) [reply test/test_va_api_get_create_config.cpp]: Yes, good catch.  I'll add VA_ENC_PACKED_HEADER_MISC to g_vaEncPackedHeaders

**Comment by uartie** [comment]
@xhaihao updated.

File: test/test_va_api_createsurfaces.cpp [hunk 10]
```diff
@@ -24,44 +24,150 @@
...
+            }
+        }
+    }
+};
+
+typedef ::testing::WithParamInterface<
+    std::tuple<VAProfile, VAEntrypoint> > QuerySurfacesParamInterface;
+
+class VAAPIQuerySurfaces
+    : public ::testing::WithParamInterface<std::tuple<VAProfile, VAEntrypoint>>
```
Comment (jayesht) [inline test/test_va_api_createsurfaces.cpp]: `QuerySurfacesParamInterface` can be used here.

File: test/test_va_api_createsurfaces.cpp [hunk 11]
```diff
@@ -24,44 +24,150 @@
...
+    , public VAAPISurfaceFixture
+{
+public:
+    VAAPIQuerySurfaces()
+        : ::testing::WithParamInterface<std::tuple<VAProfile, VAEntrypoint>>()
```
Comment (jayesht) [inline test/test_va_api_createsurfaces.cpp]: And here, too.

**Comment by uartie** [comment]
@jayesht updated createsurfaces
